# Generated by Django 4.2.23 on 2025-08-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("payable_price", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField()),
                ("date_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="reservation.businessowner",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_appointments",
                        to="reservation.customer",
                    ),
                ),
            ],
        ),
    ]
